Provide AWS Error mapping per operation we use (#1104)
Using `aws_sdk_s3::Error` directly has the chance that we throw away
some useful information in the error conversion. Breaking the errors
into Operations (simillar to how the sdk handles errors internally) we
can retain some of that top level information.

Internal AWS Errors will print certain errors, if there’s a proided
code. Otherwise they say “unhandled” which isn’t always useful.
https://github.com/awslabs/aws-sdk-rust/blob/3611b7c8306750803fc75757b97092ff6d8ba6fa/sdk/s3/src/error_meta.rs#L72-L77

An example from another Projects CI where we have very little
information. We had no clue as to what operation was causing this error.
```
thread 'etl_v2::mobile_hotspot_usage::simple_2_carriers_multiple_pubkeys' panicked at tests/integrations/etl_v2/runner.rs:80:25:
ETL failed: aws error: s3: unhandled error

Caused by:
    s3: unhandled error
```

Now, at least we’ll know which operation we can start interograting.
```
Error: aws error: put_object: unhandled error

Caused by:
    put_object: unhandled error
```